import './banner/index';
import './introduce/index'
import './card/index';
import './outline/index';
import './pricing/index';
import './swap/index';
import './question/index';
import './statistics/index';
import './setting/index';