import './style.scss';

import { 
    HomeOutlined, 
    SearchOutlined, 
    LoadingOutlined, 
    DownOutlined, 
    CaretDownOutlined,
    ControlOutlined,
    CheckOutlined,
    PlusOutlined,
    FolderAddOutlined,
    AppstoreAddOutlined,
    ArrowRightOutlined,
    ArrowLeftOutlined,
    InfoCircleOutlined,
    LeftOutlined,
    SwapOutlined,
    RightOutlined,
    FunctionOutlined,
    MinusOutlined,
    CloseCircleOutlined,
    CheckCircleOutlined,
    ExclamationCircleOutlined,
    ExclamationCircleFilled,
    DoubleLeftOutlined,
    UserOutlined,
    LockOutlined,
    PicRightOutlined,
    FileTextOutlined,
    CodeOutlined,
    FullscreenExitOutlined,
    FullscreenOutlined,
    DownloadOutlined,
    PlayCircleFilled,
    CaretRightFilled,
    HistoryOutlined,
    CloseCircleFilled,
    DoubleRightOutlined,
    CheckCircleFilled,
    MessageOutlined,
    FieldNumberOutlined,
    AppstoreOutlined,
    FacebookFilled,
    EditOutlined,
    DeleteOutlined,
    PictureFilled,
    EyeFilled,
    EditFilled,
    //RemoveUtilityFilled,
    DislikeFilled,
    CommentOutlined,
    InsertRowBelowOutlined,
    FileTextFilled,
    //GoLeftDirectivityFilled,
    PictureOutlined,
    ReconciliationFilled,
    UploadOutlined,
    LikeFilled,
    VideoCameraAddOutlined,
    VideoCameraOutlined,
    DatabaseFilled,
    FilterFilled,
    //PublishUtilityFilled,
    DeleteFilled,
    PlusCircleFilled,
    DeleteRowOutlined,
    
    BarsOutlined,
    SolutionOutlined,
    FormOutlined,
    SettingOutlined,
    ProductOutlined,
    ScheduleOutlined,
    ApiOutlined,
    MailOutlined,
    FileSearchOutlined,
    PlusCircleOutlined
    
} from '@ant-design/icons';

// 重新导出需要的图标
export { 
    PlusCircleOutlined,
    FileSearchOutlined,
    MailOutlined,
    ScheduleOutlined,
    ApiOutlined,
    ProductOutlined,
    SettingOutlined,
    DeleteRowOutlined,
    FormOutlined,
    BarsOutlined,
    SolutionOutlined,
    LikeFilled,
    VideoCameraAddOutlined,
    VideoCameraOutlined,
    DatabaseFilled,
    FilterFilled,
    //PublishUtilityFilled,
    DeleteFilled,
    PlusCircleFilled,
    
    FileTextFilled,
    //GoLeftDirectivityFilled,
    PictureOutlined,
    ReconciliationFilled,
    UploadOutlined,
    EyeFilled,
    EditFilled,
    //RemoveUtilityFilled,
    DislikeFilled,
    CommentOutlined,
    InsertRowBelowOutlined,
    DeleteOutlined,
    PictureFilled,
    EditOutlined,
    FacebookFilled,
    AppstoreOutlined,
    CheckCircleFilled,
    MessageOutlined,
    DoubleRightOutlined,
    FullscreenOutlined,
    DownloadOutlined,
    PlayCircleFilled,
    CaretRightFilled,
    HistoryOutlined,
    CloseCircleFilled,
    
    FieldNumberOutlined,
    UserOutlined,
    FullscreenExitOutlined,
    CodeOutlined,
    FileTextOutlined,
    PicRightOutlined,
    LockOutlined,
    DoubleLeftOutlined,
    ExclamationCircleOutlined,
    ExclamationCircleFilled,
    HomeOutlined, 
    CheckCircleOutlined,
    CloseCircleOutlined,
    MinusOutlined,
    SwapOutlined,
    FunctionOutlined,
    SearchOutlined, 
    LoadingOutlined, 
    DownOutlined, 
    CaretDownOutlined ,
    ControlOutlined,
    CheckOutlined,
    PlusOutlined,
    FolderAddOutlined,
    AppstoreAddOutlined,
    ArrowRightOutlined,
    ArrowLeftOutlined,
    InfoCircleOutlined,
    LeftOutlined,
    RightOutlined
};

export * from './assets/index';

export { default as CombineIcon } from './CombineIcon';



